"""
utils/db/ — التخزين الدائم (SQLite)

قبل هذه الطبقة كان كل شيء في session_state ويضيع بإغلاق المتصفح. الآن:
  · كل منافسة مشروع مستقل له تحليلاته وأقسامه وجداوله وملاحظات مراجعته.
  · ملف الشركة يُحفظ مرة واحدة ويُشارَك بين كل المنافسات.
  · مستودع المعرفة (مستندات + متجهات التضمين) يُحفظ للشركة كذلك.

قاعدة البيانات ملف واحد على القرص — لا خادم ولا خدمة خارجية، اتساقاً مع كون
النظام يعمل محلياً وبيانات العطاءات لا تغادر الجهاز.

كانت وحدةً واحدة من ٢٬٧٩٢ سطراً يمسّها كل متطلب جديد. قُسّمت حزمةً بوحدة لكل
مجال، و**الواجهة لم تتغيّر**: `from utils import db` ثم `db.save_project(...)`
يعمل كما كان، لأن هذا الملف يعيد تصدير كل اسم كانت الوحدة تعرضه — العام
والخاص معاً، إذ تستدعي الاختبارات `db._scope` و `db._replace_records`.

خريطة الاعتماد **بلا دورات**: `_core` لا تعتمد على شيء، وكل وحدة تعتمد عليها،
و`privacy` وحدها تعتمد على أخوات (وهي ورقة لا يعتمد عليها أحد).
"""

# **لا يُعاد تصدير `_active_company_id` ولا `_company_resolver`** عمداً: كلاهما
# يُسنَد من جديد داخل `_core` بـ `global`، وإعادة التصدير تنسخ *الارتباط* لا
# تتابعه — فيبقى `db._active_company_id` على القيمة القديمة بعد
# `set_active_company()`، ويقرأ من يثق به قيمةً ميتة بلا خطأ يُرفع. اقرأهما
# عبر `active_company_id()` وحدها، وهي تقرأ العام في موضعه.

from ._core import (  # noqa: F401
    ANY_COMPANY,
    APP_DIR,
    COMPANY_SCOPED_TABLES,
    DATA_DIR,
    DB_PATH,
    SCHEMA,
    UNSCOPED_COMPANY,
    active_company_id,
    company_exists,
    get_conn,
    list_companies,
    oldest_company_id,
    set_active_company,
    set_company_resolver,
    transaction,
    _local,
    _scope,
)

from .snapshots import (  # noqa: F401
    REQUIRED_TABLES,
    SQLITE_MAGIC,
    restore_bytes,
    snapshot_bytes,
    validate_snapshot,
)

from .projects import (  # noqa: F401
    APPROVAL_STAGES,
    APPROVED,
    REJECTED,
    SECTION_VERSION_LIMIT,
    add_audit_entry,
    add_section_version,
    approval_state,
    approvals_complete,
    count_audit_entries,
    create_project,
    delete_approvals,
    delete_project,
    delete_section_versions,
    duplicate_project,
    get_section_version,
    latest_audit_entry,
    list_approvals,
    list_audit_entries,
    list_projects,
    list_section_versions,
    load_project,
    next_approval_stage,
    project_revision,
    prune_section_versions,
    record_approval,
    save_project,
    set_outcome,
)

from .accounts import (  # noqa: F401
    clear_company_template,
    company_holdings,
    count_users,
    create_company,
    create_user,
    delete_company,
    delete_user,
    get_user,
    get_user_by_id,
    list_users,
    load_company,
    rename_company,
    save_company,
    set_user_active,
    set_user_company,
    set_user_password,
    set_user_role,
    touch_user_login,
    update_user_profile,
)

from .knowledge import (  # noqa: F401
    BLOCK_APPROVED,
    BLOCK_DRAFT,
    BLOCK_RETIRED,
    BLOCK_STATUSES,
    DEFAULT_REVIEW_MONTHS,
    add_figure,
    add_kb_chunks,
    add_kb_document,
    all_kb_chunks,
    approved_blocks,
    block_review_due,
    content_block_by_key,
    content_block_stats,
    delete_content_block,
    delete_entity_template,
    delete_figure,
    delete_kb_document,
    delete_project_figures,
    delete_prompt,
    entity_template,
    get_content_block,
    kb_stats,
    list_content_blocks,
    list_entity_templates,
    list_figures,
    list_kb_documents,
    list_prompts,
    mark_block_reviewed,
    prompt_override,
    record_block_use,
    save_content_block,
    save_entity_template,
    save_prompt,
    set_block_status,
    set_prompt_enabled,
    update_figure,
)

from .delivery import (  # noqa: F401
    CLARIFY_ANSWERED,
    CLARIFY_CLOSED,
    CLARIFY_DRAFT,
    CLARIFY_SENT,
    CLARIFY_STATUSES,
    DELIVERABLE_DONE,
    DELIVERABLE_DROPPED,
    DELIVERABLE_OPEN,
    DELIVERABLE_STATUSES,
    SOURCE_MANUAL,
    SOURCE_MATRIX,
    SOURCE_SECTION,
    add_clarification,
    add_deliverable,
    answer_clarification,
    close_clarification,
    create_delivery,
    delete_clarification,
    delete_deliverable,
    delete_delivery,
    delete_project_clarifications,
    get_clarification,
    get_delivery,
    list_clarifications,
    list_deliverables,
    list_deliveries,
    mark_clarification_sent,
    project_costs,
    update_clarification,
    update_deliverable,
)

from .reference import (  # noqa: F401
    DEFAULT_LEGAL_BASIS,
    DEFAULT_RETENTION_MONTHS,
    LEGAL_BASES,
    app_setting,
    clear_all_permission_overrides,
    clear_permission_override,
    connector_order,
    delete_glossary_term,
    forget_connector_order,
    glossary_by_term,
    glossary_term,
    list_glossary,
    permission_override,
    permission_overrides,
    personal_data_policy,
    preferred_form,
    record_connector_order,
    save_glossary_term,
    set_app_setting,
    set_connector_order_remote,
    set_permission_override,
    set_personal_data_policy,
)

from .privacy import (  # noqa: F401
    add_attachment_version,
    delete_attachment_version,
    expired_cv_documents,
    forget_person,
    list_attachment_versions,
    load_attachment_version,
    person_footprint,
    previous_attachment_version,
)

from .records import (  # noqa: F401
    find_entity,
    list_records,
    record_counts,
    save_records,
    _replace_records,
)

from .usage import (  # noqa: F401
    ai_cache_clear,
    ai_cache_get,
    ai_cache_put,
    kb_chunk_texts,
    kb_stale_chunk_count,
    log_ai_usage,
    update_kb_chunk_embeddings,
    usage_month_cost,
    usage_summary,
    usage_totals,
)

# `pyflakes` لا يفهم `# noqa`، و`__all__` هو ما يجعل إعادة التصدير
# استعمالاً في نظره — وهي خطوة حاجزة في CI.
__all__ = [
    # الثلاثة الخاصّة أدناه مقصودة: تستدعيها الاختبارات عبر `db.` مباشرةً،
    # ووجودها في `__all__` هو ما يجعل إعادة تصديرها استعمالاً عند pyflakes.
    "_local",
    "_replace_records",
    "_scope",
    "ANY_COMPANY",
    "APPROVAL_STAGES",
    "APPROVED",
    "APP_DIR",
    "BLOCK_APPROVED",
    "BLOCK_DRAFT",
    "BLOCK_RETIRED",
    "BLOCK_STATUSES",
    "CLARIFY_ANSWERED",
    "CLARIFY_CLOSED",
    "CLARIFY_DRAFT",
    "CLARIFY_SENT",
    "CLARIFY_STATUSES",
    "COMPANY_SCOPED_TABLES",
    "DATA_DIR",
    "DB_PATH",
    "DEFAULT_LEGAL_BASIS",
    "DEFAULT_RETENTION_MONTHS",
    "DEFAULT_REVIEW_MONTHS",
    "DELIVERABLE_DONE",
    "DELIVERABLE_DROPPED",
    "DELIVERABLE_OPEN",
    "DELIVERABLE_STATUSES",
    "LEGAL_BASES",
    "REJECTED",
    "REQUIRED_TABLES",
    "SCHEMA",
    "SECTION_VERSION_LIMIT",
    "SOURCE_MANUAL",
    "SOURCE_MATRIX",
    "SOURCE_SECTION",
    "SQLITE_MAGIC",
    "UNSCOPED_COMPANY",
    "active_company_id",
    "add_attachment_version",
    "add_audit_entry",
    "add_clarification",
    "add_deliverable",
    "add_figure",
    "add_kb_chunks",
    "add_kb_document",
    "add_section_version",
    "ai_cache_clear",
    "ai_cache_get",
    "ai_cache_put",
    "all_kb_chunks",
    "answer_clarification",
    "app_setting",
    "approval_state",
    "approvals_complete",
    "approved_blocks",
    "block_review_due",
    "clear_all_permission_overrides",
    "clear_company_template",
    "clear_permission_override",
    "close_clarification",
    "company_exists",
    "company_holdings",
    "connector_order",
    "content_block_by_key",
    "content_block_stats",
    "count_audit_entries",
    "count_users",
    "create_company",
    "create_delivery",
    "create_project",
    "create_user",
    "delete_approvals",
    "delete_attachment_version",
    "delete_clarification",
    "delete_company",
    "delete_content_block",
    "delete_deliverable",
    "delete_delivery",
    "delete_entity_template",
    "delete_figure",
    "delete_glossary_term",
    "delete_kb_document",
    "delete_project",
    "delete_project_clarifications",
    "delete_project_figures",
    "delete_prompt",
    "delete_section_versions",
    "delete_user",
    "duplicate_project",
    "entity_template",
    "expired_cv_documents",
    "find_entity",
    "forget_connector_order",
    "forget_person",
    "get_clarification",
    "get_conn",
    "get_content_block",
    "get_delivery",
    "get_section_version",
    "get_user",
    "get_user_by_id",
    "glossary_by_term",
    "glossary_term",
    "kb_chunk_texts",
    "kb_stale_chunk_count",
    "kb_stats",
    "latest_audit_entry",
    "list_approvals",
    "list_attachment_versions",
    "list_audit_entries",
    "list_clarifications",
    "list_companies",
    "list_content_blocks",
    "list_deliverables",
    "list_deliveries",
    "list_entity_templates",
    "list_figures",
    "list_glossary",
    "list_kb_documents",
    "list_projects",
    "list_prompts",
    "list_records",
    "list_section_versions",
    "list_users",
    "load_attachment_version",
    "load_company",
    "load_project",
    "log_ai_usage",
    "mark_block_reviewed",
    "mark_clarification_sent",
    "next_approval_stage",
    "oldest_company_id",
    "permission_override",
    "permission_overrides",
    "person_footprint",
    "personal_data_policy",
    "preferred_form",
    "previous_attachment_version",
    "project_costs",
    "project_revision",
    "prompt_override",
    "prune_section_versions",
    "record_approval",
    "record_block_use",
    "record_connector_order",
    "record_counts",
    "rename_company",
    "restore_bytes",
    "save_company",
    "save_content_block",
    "save_entity_template",
    "save_glossary_term",
    "save_project",
    "save_prompt",
    "save_records",
    "set_active_company",
    "set_app_setting",
    "set_block_status",
    "set_company_resolver",
    "set_connector_order_remote",
    "set_outcome",
    "set_permission_override",
    "set_personal_data_policy",
    "set_prompt_enabled",
    "set_user_active",
    "set_user_company",
    "set_user_password",
    "set_user_role",
    "snapshot_bytes",
    "touch_user_login",
    "transaction",
    "update_clarification",
    "update_deliverable",
    "update_figure",
    "update_kb_chunk_embeddings",
    "update_user_profile",
    "usage_month_cost",
    "usage_summary",
    "usage_totals",
    "validate_snapshot",
]
